### ISSUE TITLE
ProductPayRequest signing

### ISSUE THREAD

**Issue by Deroido** [mmontesinos81/HMSPlugin#2]
Hello.
There's a code in the example:

```
        ProductPayRequest request = new ProductPayRequestBuild()
            .Info("Test 2", productID, DateTime.Now.ToString("yyyyMMddhhmmssfff"))
            .OptServiceCatalog("X6")
            .RsaSign(key)

            .Build();

        Purchasing.ProductPay(request, new ProductPayImpl());
```

Though I received prices but I can't make a purchase out of the box. It shows an error:

> 2020/03/25 14:15:07.041 14891 14934 Error HMSAgent null(-2)->SignUtility(64)->PaySignUtil(412)->rsaSign
2020/03/25 14:15:07.041 14891 14934 Error HMSAgent rsaSign error
2020/03/25 14:15:07.067 14891 14934 Error Unity ArgumentNullException: Value cannot be 
 null.

So we have to specify OptKey as well. or use altered 'key':
In official Java sdk you have to sign each request like this:
`payReq.sign = PaySignUtil.rsaSign(PaySignUtil.getStringForSign(payReq), pay_priv_key);`
but there's no similar functionality in HMSPlugin.

Could you help me with that? Or explain more please.
What sign do we use here? 

![image](https://user-images.githubusercontent.com/201954/77534286-ebfe9280-6eca-11ea-9818-9709fe36238f.png)

**Comment by mmontesinos81** [comment]
Hello,

Sorry for the delay, but this project has been discontinued, please check the new iniciative [here](https://github.com/EvilMindDevs/hms-unity-plugin)
